/*
  Simple Fish Bowl
  by YouniqueĪdeaStudio (https://sketchfab.com/sinnervoncrawsz)
  via https://sketchfab.com/3d-models/simple-fish-bowl-dfd5807cadd1480785dfe45349d8182a
  
  License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
  Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import type { ObjectMap } from '@react-three/fiber'
import { type JSX } from 'react'
import { Mesh, MeshPhysicalMaterial } from 'three'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF &
  ObjectMap & {
    nodes: {
      BOL001__0: Mesh
    }
    materials: {
      ['Scene_-_Root']: MeshPhysicalMaterial
    }
  }

export function FishBowl(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./models/fish-bowl.glb') as GLTFResult

  return (
    <mesh
      {...props}
      dispose={null}
      castShadow
      receiveShadow
      geometry={nodes.BOL001__0.geometry}
      material={materials['Scene_-_Root']}
      position={[31.054, 0, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
  )
}

useGLTF.preload('./models/fish-bowl.glb')
