/*
  Fishing Pole
  by Shawn Westphal [CC-BY] (https://creativecommons.org/licenses/by/3.0/)
  via Poly Pizza (https://poly.pizza/m/eyuCxAqI9er)

  Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei'
import type { ObjectMap } from '@react-three/fiber'
import { useEffect, type JSX } from 'react'
import type { Mesh, MeshStandardMaterial } from 'three'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF &
  ObjectMap & {
    nodes: {
      ['Group#5-Entity38825']: Mesh
      ['Group#7-Entity38827']: Mesh
    }
    materials: {
      FrontColor: MeshStandardMaterial
      ['[0038_Orange]']: MeshStandardMaterial
    }
  }

export default function FishingPole(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./models/fishing-pole.glb') as GLTFResult

  useEffect(() => {
    materials.FrontColor.color.set('goldenrod')
    materials.FrontColor.metalness = 0.8
    materials.FrontColor.roughness = 0.5

    materials['[0038_Orange]'].color.set('sienna')
  }, [materials])

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        geometry={nodes['Group#5-Entity38825'].geometry}
        material={materials['[0038_Orange]']}
      />
      <mesh
        castShadow
        geometry={nodes['Group#7-Entity38827'].geometry}
        material={materials.FrontColor}
      />
    </group>
  )
}

useGLTF.preload('./models/fishing-pole.glb')
