/*
  Fish
  by Zainal Abd. Kahar (https://sketchfab.com/zsuperxtreme)
  via https://sketchfab.com/3d-models/fish-80d9d61f143c472b8e1522a2fd711f9e
  
  License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
  Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei'
import type { ObjectMap } from '@react-three/fiber'
import { useEffect, type JSX } from 'react'
import type { ColorRepresentation, Mesh, MeshStandardMaterial } from 'three'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF &
  ObjectMap & {
    nodes: {
      Sphere_Color_0: Mesh
      Mouth_Color_0: Mesh
      Eyes_Color_0: Mesh
      Iris_Color_0: Mesh
      Fin_Color_0: Mesh
      Tail_Color_0: Mesh
      FinLeft_Color_0: Mesh
      Sphere001_Color_0: Mesh
      Sphere002_Color_0: Mesh
      Sphere003_Color_0: Mesh
    }
    materials: {
      Color: MeshStandardMaterial
    }
  }

type FishProps = JSX.IntrinsicElements['group'] & {
  colorA?: ColorRepresentation
  colorB?: ColorRepresentation
  colorC?: ColorRepresentation
}

export default function Fish({
  colorA = 'white',
  colorB = 'white',
  colorC = 'white',
  ...props
}: FishProps) {
  const { nodes, materials } = useGLTF('./models/fish.glb') as GLTFResult

  useEffect(() => {
    materials.Color.metalness = 0.2
    materials.Color.roughness = 0.8
  }, [materials])

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            geometry={nodes.Sphere_Color_0.geometry}
            position={[0, 231.474, 6.24]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={140.754}
          >
            <meshStandardMaterial {...materials.Color} map={undefined} color={colorA} />
          </mesh>
          <mesh
            castShadow
            geometry={nodes.Mouth_Color_0.geometry}
            material={materials.Color}
            position={[0, 193.086, 149.114]}
            rotation={[-2.857, 0, -Math.PI]}
            scale={[-4.96, 4.96, 6.644]}
          />
          <mesh
            castShadow
            geometry={nodes.Eyes_Color_0.geometry}
            material={materials.Color}
            position={[0, 240.885, 135.691]}
            rotation={[-1.679, 0, 0]}
            scale={[40.677, 24.659, 49.608]}
          />
          <mesh
            castShadow
            geometry={nodes.Iris_Color_0.geometry}
            material={materials.Color}
            position={[0, 240.885, 158.506]}
            rotation={[-1.679, 0, 0]}
            scale={[12.905, 7.823, 15.739]}
          />
          <mesh
            castShadow
            geometry={nodes.Fin_Color_0.geometry}
            position={[0, 311.063, 5.449]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={100}
          >
            <meshStandardMaterial {...materials.Color} color={colorB} />
          </mesh>
          <mesh
            castShadow
            geometry={nodes.Tail_Color_0.geometry}
            position={[0, 238.314, -111.059]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={100}
          >
            <meshStandardMaterial {...materials.Color} color={colorB} />
          </mesh>
          <mesh
            castShadow
            geometry={nodes.FinLeft_Color_0.geometry}
            position={[0.744, 232.616, 28.922]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <meshStandardMaterial {...materials.Color} color={colorB} />
          </mesh>
          <mesh
            castShadow
            geometry={nodes.Sphere001_Color_0.geometry}
            position={[0, 231.474, 6.24]}
            rotation={[-1.149, 0.616, 0.197]}
            scale={140.754}
          >
            <meshStandardMaterial {...materials.Color} color={colorC} />
          </mesh>
          <mesh
            castShadow
            geometry={nodes.Sphere002_Color_0.geometry}
            position={[0, 231.474, 6.24]}
            rotation={[-0.478, -0.674, 1.824]}
            scale={140.754}
          >
            <meshStandardMaterial {...materials.Color} color={colorC} />
          </mesh>
          <mesh
            castShadow
            geometry={nodes.Sphere003_Color_0.geometry}
            position={[0, 231.474, 6.24]}
            rotation={[-1.436, -0.619, 0.373]}
            scale={140.754}
          >
            <meshStandardMaterial {...materials.Color} color={colorC} />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/fish.glb')
