/*
    Tuft of grass 
    by Poly by Google [CC-BY] (https://creativecommons.org/licenses/by/3.0/) 
    via Poly Pizza (https://poly.pizza/m/3tyh15Fbmsx)

    Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei'
import type { ObjectMap } from '@react-three/fiber'
import { type JSX } from 'react'
import type { Mesh, MeshStandardMaterial } from 'three'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF &
  ObjectMap & {
    nodes: {
      Plane002: Mesh
      Plane003: Mesh
      Plane004: Mesh
      Plane005: Mesh
      Plane006: Mesh
      Plane007: Mesh
      Plane008: Mesh
      Plane009: Mesh
      Plane010: Mesh
      Plane011: Mesh
      Plane012: Mesh
      Plane013: Mesh
      Plane014: Mesh
      Plane015: Mesh
      Plane016: Mesh
      Plane017: Mesh
      Plane018: Mesh
      Plane019: Mesh
      Plane020: Mesh
      Plane021: Mesh
      Plane022: Mesh
      Plane023: Mesh
      Plane024: Mesh
      Plane025: Mesh
      Plane026: Mesh
      Plane027: Mesh
      Plane028: Mesh
      Plane029: Mesh
    }
    materials: {
      _crayfishdiffuse: MeshStandardMaterial
    }
  }

export default function Grass(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./models/grass.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane019.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane021.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane022.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane023.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane028.geometry}
        material={materials._crayfishdiffuse}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane029.geometry}
        material={materials._crayfishdiffuse}
      />
    </group>
  )
}

useGLTF.preload('./models/grass.glb')
